import { createGatewayRuntime } from '@graphql-hive/gateway-runtime';
import { buildSchema } from 'graphql';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read the supergraph schema generated by mesh-compose
const supergraphSdl = readFileSync(join(__dirname, 'hive/supergraph.graphqls'), 'utf8');

export const gateway = createGatewayRuntime({
  supergraph: buildSchema(supergraphSdl)
});

export default gateway;
